### PR TITLE
forth: bump the version to 1.7.1 (no changes needed)

### PR DESCRIPTION
**Pull request by sharno**
I checked with the changes:
https://github.com/exercism/problem-specifications/commit/75f4c0a8c86cd5140dc5e8f29ebbd6e728bc5025

There seem to be no typos in the haskell test descriptions, hence just a version bump

### CODE REVIEW

**Comment by petertseng** [comment]
Please do include the link to the PR in the commit message, not just in the PR description. Thank you.

**Comment by sharno** [comment]
Fixed the commit message to include the original PR link

**Comment by petertseng** [comment]
Thank you!

(Also I like to put the exercise name as the very first thing in the commit message, but I'm not sure if that is a universal preference...)

**Comment by petertseng** [comment]
(For the record, regarding my usual behaviour of "give other maintainers time to respond", I had sort of inferred that other maintainers had looked and found no further issues, but do feel free to correct me if I was in the wrong here)

**Comment by sshine** [comment]
> I like to put the exercise name as the very first thing in the commit message

So do I.

> I had sort of inferred that other maintainers had looked and found no further issues

Your inference was correct.

**Pull request merged**
