### PR TITLE
Add hiljusti as a maintainer

### PR DESCRIPTION
**Pull request by hiljusti**
I've been helping out on some other tracks, but would like to assist here every once in a while with reviews.

### CODE REVIEW

**Comment by petertseng** [comment]
While I have not personally worked together with hiljusti, if Exercism central leadership endorses, I will trust their judgment.

To commemorate this occasion, I believe I fixed CI, so reviews can proceed assuming that CI should remain successful, and failures should be looked into instead of approving.

I would like to ask that sshine's resignation from #982 be included with this PR, so I added the commit. That PR was closed because the fork was deleted, but it is clear that sshine does intend to resign (fork deleted, no longer watching repo). The fork being deleted means the PR can't just be reopened. So let's include the two together so maintainers-admin only has to review one PR.

Please do not squash commits when merging since adding one person and removing another are two separate operations.

**Comment by petertseng** [comment]
EBWODP: 

> sshine's resignation from #982 

My apologies. I meant to say sshine's resignation from #962 . The numbers were too similar and I got mixed up.

**Comment by petertseng** [comment]
> if Exercism central leadership endorses, I will trust their judgment.

On the other hand, if Exercism central leadership is neutral, then my opinion is to be cautious, consider starting small, but to proceed with this PR if reasoned judgment says to do so. More details below.

I understand that hiljusti opened a lot of these PRs for a lot of tracks. I have read https://github.com/exercism/erlang/pull/476#issuecomment-858345289 and understand that hiljusti does have an interest in all these languages. I comment that it has historically been unusual for a maintainer to be added out of the blue to a track without any prior history of contribution to that track, but acknowledge that:

1. times are changing with exercism v3, and so too may be the way we do things around here, and
2. since I'm not the most active of maintainers either, I shouldn't stand in the way if Exercism central leadership wishes to appoint one whom they have worked with and therefore have confidence will improve this track as a result of being one.

I believe most people involved with this PR have read https://github.com/exercism/docs/pull/136, and thus we understand the tasks that would come alongside maintainership. My personal experience is that I have never been able to successfully be a maintainer for more than four tracks at a time, and even that was a stretch. But, each person has a different set of individual circumstances - for example, one prolific Exercism polyglot maintainer I know of is a maintainer of eight different tracks. So I cannot say how many tracks is too many for anyone but myself, but I will caution that past a certain point, everyone finds that something has to give.

Now, on the one hand I would say that a lot of tasks (reviewing PRs, submitting PRs, etc.) can be done even while not being a maintainer. But on the other hand I understand that being a maintainer may have the effect of encouraging more of that, due to the added sense of responsibility. It's not easy to get contributions for tracks, and even though I have not actively worked on this track since November 2020, I should continue to do all I can to encourage contributions. So, whatever route we take that will have this effect is one I should endorse.

**Comment by iHiD** [comment]
@petertseng Thank you for your thoughts and comments. I've not spoken to @hiljusti today but I am happy for him to join the Haskell track if he'd like to take an active role in it, or for him to contribute via `@exercism/reviewers` if he'd like to help review, etc. I agree entirely with the demarcations you've outlined.

I also agree we should merge 17790ac either way. I had thought that @sshine had simply changed his mind on that resignation, but now I sadly realise that it was intentional but unmerged.

**Comment by petertseng** [comment]
Since we have agreement on  6d82097 and will wait for hiljusti's response on the other, I think I'll separate the PRs again so that they can be processed separately.

**Comment by petertseng** [comment]
Since we have agreement on 17790ac and will wait for hiljusti's response on the other, I think I'll separate the PRs again so that they can be processed separately.

**Comment by hiljusti** [comment]
Sorry for the noise - I love Haskell, but I think what I really wanted was just to be in `exercism/reviewers` to help out on smaller things across many tracks.

I might still do some PRs or something in the future though

**Pull request closed without merging**
