### PR TITLE
update/complete haskell tags

### LINKED ISSUE #939: [v3] Add tags
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

In Exercism v3, tracks can be annotated with tags. This allows searching for tracks with a certain tag combination, making it easy for students to find an interesting track to join.

Tags are specified in the top-level `"tags"` field in the track's `config.json` file and are defined as an array of strings, as specified in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#tags).

## Goal

The `"tags"` field in the `config.json` file should be updated to contain the tags that are relevant to this track. The list of tags that can be used is listed in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#tags).

## Example

```json
{
  "tags": [
    "runtime/jvm",
    "platform/windows",
    "platform/linux",
    "paradigm/declarative",
    "paradigm/functional",
    "paradigm/object_oriented"
  ]
}
```

## Tracking

https://github.com/exercism/v3-launch/issues/1

### PR DESCRIPTION
**Pull request by gacallea**
fixes https://github.com/exercism/exercism/issues/6610
fixes #939

### CODE REVIEW

**Comment by MatthijsBlom** [comment]
@gacallea Presently `paradigm/declarative` is marked as justified but not present in the tag list.

Other than that, do you have anything to add? If not, I'll approve.

**Comment by gacallea** [comment]
> @gacallea Presently `paradigm/declarative` is marked as justified but not present in the tag list. Do you disagree with the justification, or is it just an oversight?
> 
> Other than that, do you have anything to add? If not, I'll approve.

Hi Matt, tbh I'm not sure. The reason I didn't put it is because Tags.md said "implicit with functional" so I thought it was going to be automatic. Bottom line: IF all other FP langs do have it, I'm going to add it here as well. Let me know :)

**Comment by gacallea** [comment]
@MatthijsBlom better still: official wiki doesn't define it as declarative. I'd leave it out.

https://wiki.haskell.org/Introduction

**Comment by gacallea** [comment]
pps: (sorry for the spam). Declarative suits languages as Prolog but not Haskell or similar FP. It is nitpicking but I'd not add declarative to FP langs that aren't "marked as such" from official resources.

**Comment by MatthijsBlom** [comment]
Going by Wikipedia (e.g. «[Functional programming](https://en.wikipedia.org/wiki/Functional_programming)», «[Declarative programming](https://en.wikipedia.org/wiki/Declarative_programming#Functional_programming)»), declarative languages form a superset of both functional languages and logical languages.

The section «[What is functional programming](https://wiki.haskell.org/Introduction#What_is_functional_programming.3F)» explicitly says that functional programming emphasizes the _what_ over the _how_.

**Comment by gacallea** [comment]
no problem then. If wikipedia is the primary source, then I'm ok with it. I usually prefer official sources if available. modifying the file :)

**Comment by MatthijsBlom** [comment]
It seems I'm not allowed to Approve.

@petertseng I think this is mergeable.

**Review by kytrinyx — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]
I like how you've documented the choices made.

**Comment by gacallea** [comment]
hi :)

I was wondering if there are any stoppers for this merge? Anything I should do?

please and thank you

**Comment by ErikSchierboom** [comment]
@gacallea I'd like @petertseng to also look at this, as he's the resident Haskell maintainer.

**Comment by gacallea** [comment]
> @gacallea I'd like @petertseng to also look at this, as he's the resident Haskell maintainer.

@ErikSchierboom ok thank you :) i appreciate.

**Comment by ErikSchierboom** [comment]
@gacallea If Peter hasn't found time to review in a couple of days, let me know and I'll merge.

**Comment by gacallea** [comment]
yay! thank you all :)

**Pull request merged**
