### PR TITLE
stack.yaml: lts-14.7 -> lts-15.8

### PR DESCRIPTION
**Pull request by tejasbubane**
https://www.stackage.org/diff/lts-14.7/lts-15.8

Last update 6 months ago #846

I have confirmed that no README check is needed

### CODE REVIEW

**Comment by tejasbubane** [comment]
@sshine Build passed.

**Comment by sshine** [comment]
@tejasbubane: Excellent.

@kytrinyx, @iHiD: Could we please get "merge commit" and "rebase and merge" back? I requested "merge commit" back some weeks ago, but this resulted in losing "rebase and merge" instead, and we haven't had that many PRs since then. In this particular case I'd like "merge commit", but most often I'd like "rebase and merge".

**Comment by iHiD** [comment]
All three are back on now :)

**Comment by sshine** [comment]
@ihid: "Create a merge commit" still says "Not enabled for this branch."

In the process of learning why that is, in case this particular PR remembers things from before the setting was flipped, shall I bring it up again if/when another PR cannot be merged, rather than we try and fix our merge options on a commit made before in time from changing the setting?

**Comment by sshine** [comment]
I've rebased because both commits explain themselves well.

**Pull request merged**
