### PR TITLE
Adds concept Booleans

### PR DESCRIPTION
**Pull request by pwadsworth**
Adds Booleans concept adapted from the F# track. 

Exercise Annalyn's Infiltration to follow.

### CODE REVIEW

**Comment by pwadsworth** [comment]
Addressed issue [Reference directory structure does not match current use. #1082](https://github.com/exercism/haskell/issues/1082)

**Comment by petertseng** [comment]
Indentation was removed from the concepts lists. I have no records of us deciding that it should be removed. Indentation should be restored.

**Comment by petertseng** [comment]
You should put the documentation changes into their own PR. I won't refuse to review it but it makes no sense to delay one based on the other.

**Comment by pwadsworth** [comment]
> 

I'll be happy to if you point me in the right direction. I haven't figured out how to make separate PRs. Every time I update my fork and then do a PR to this one, the new PR is added to any open one I have. I'd rather make multiple small PRs.

**Comment by pwadsworth** [comment]
> Indentation was removed from the concepts lists. I have no records of us deciding that it should be removed. Indentation should be restored.

Oops. Didn't mean to do that. I'll correct it.

**Comment by petertseng** [comment]
A pull request contains any commits that are added to the designated branch. The designated branch for this PR is the `main` branch on `pwadsworth/haskell`.

Therefore:

Create a branch, put the desired commits on it, and open a pull request, with that branch as the designated branch.

**Comment by pwadsworth** [comment]
I just figure out how. Closing this PR to open separate ones.

**Pull request closed without merging**
