### PR TITLE
Ensure readmes are updated

### PR DESCRIPTION
**Pull request by sshine**
I didn't want to beat you to it, @petertseng, since you offered to do this.

But I figured this would be a good exercise for me to get to know the maintainer pipeline.

Fixes build problem in #773.

### CODE REVIEW

**Comment by petertseng** [comment]
> I didn't want to beat you to it

I admit being a little perplexed by this statement, given the existence of #777, but I'll roll with it.

So if you would like these commits merged, I would like to ask that each commit contains references to the problem-specifications PRs that caused the changes.

If that sounds like too much work, well for this particular case, lucky for you, since I already did it, but if it sounds like too much work for the future, we should talk about that!

**Comment by sshine** [comment]
>_< Oops, I should be more observant. I'll close this one.

Thanks for your patience.

**Comment by petertseng** [comment]
Well, no worries, you statement of

> I figured this would be a good exercise for me to get to know the maintainer pipeline.

is undoubtedly true, so that could help prepare you for later. And the knowledge should be applicable to your other tracks as well.

**Comment by petertseng** [comment]
That first commit in this PR could be useful to have though. So if you want that, you could consider reopening this PR and putting only this commit on there!

**Comment by sshine** [comment]
Will do.

**Comment by sshine** [comment]
I'm sorry, I pushed the button too fast.

**Comment by petertseng** [comment]
Was there a problem? Did you want to do something before pushing the button?

**Comment by petertseng** [comment]
Oh, I guess if it's about the commit messages and/or PR title - that is not really so terrible.

But it is true that sometimes I will take an action along the lines of "Approve, assuming you make these changes before merging" versus "Approve, and no changes are needed", and I can do a better job of distinguishing between these cases?

In this case, I didn't really care too much.

**Comment by sshine** [comment]
I'll read the message on PC, that should be sufficient. :-)

**Pull request merged**
