### PR TITLE
Revert "[DO NOT MERGE] Test"

### PR DESCRIPTION
**Pull request by iHiD**
Reverts exercism/haskell#909 (cc @sshine - let's get this one working).

### CODE REVIEW

**Comment by sshine** [comment]
@petertseng: Can you confirm if merge-commit is available to you?

**Comment by petertseng** [comment]
Not enabled for this branch.

**Comment by iHiD** [comment]
Now?

**Comment by sshine** [comment]
Yes, now!

**Comment by iHiD** [comment]
OK, great. So I have to disable the branch protection for "Enforce linear commits"

**Comment by iHiD** [comment]
And it looked fine to me, because I'm an administrator so can override.

**Comment by sshine** [comment]
Good to know.

**Comment by iHiD** [comment]
I've changed SML too for you.

**Comment by sshine** [comment]
In that case, could you also change: ocaml, tcl

**Comment by iHiD** [comment]
Done.

**Pull request merged**
