### PR TITLE
Concept exercise guessing-game (new)

### LINKED ISSUE #1092: Implement Concept Exercise for pattern matching: Guessing Game
We'd like to introduce pattern matching, and we think Guessing Game is a suitable story for this:
https://exercism.org/docs/building/tracks/stories/pattern-matching-number-guessing-game

Both Elixir and F# have implemented this exercise, so it's worth taking a look at those implementations to see if there's anything there that is useful to us here.

- F#: https://github.com/exercism/fsharp/tree/main/exercises/concept/guessing-game
- Elixir: https://github.com/exercism/elixir/tree/main/exercises/concept/guessing-game

Here's a sample code snippet courtesy of @MatthijsBlom that might be suitable as a starting point.
 
```
reply 41 = SoClose
reply 42 = Correct
reply 43 = SoClose
reply n  = if n < 42 then TooLow else TooHigh
```

We will introduce pattern matching in more depth over time, so in this first exercise we'd like to explain _just enough_ to let students complete the exercise. We should also explain enough about types so that `SoClose`, `Correct` and friends aren't mystifying.

To start out, let's just get a sample solution, test suite, and stub together so that we can discuss (both in terms of Haskell and in terms of Exercism Concept Exercises).

After that in follow-on PRs we can develop the instructions (which can then be tested and discussed), and then finally the introduction.

The concept will also need to be worked on. We can do that at the same time as the introduction, or we can start on it earlier. I'm not opening an issue for it yet, but if you want to work on that drop a note in the discussion below so that we know it's being worked on.

Note that we're still working out how to best work with contributors on these concept exercises. If you have questions, please holler! We'll do our best to help figure out how to proceed.

### PR DESCRIPTION
**Pull request by pwadsworth**
Adds concept exercise Guessing Game for concept Pattern Matching.
Closes #1092 and fixes my mess in PR #1094

### CODE REVIEW

**Comment by petertseng** [comment]
In this case, it is not a problem, but there are some times where it won't be appropriate to open a new pull request. These are cases where there is significant discussion in the previous pull request and further discussion is required in the new one. Opening a new pull request would split the discussion into two places, which means it is not possible to follow the discussion. That is not the case here, so we are okay.

But this pull request has demonstrated that you were able to create a branch that contains just the two commits you want merged, which is good! In that case, the course of action would to push those two commits to the `guessing-game` branch, the branch being used in https://github.com/exercism/haskell/pull/1094, not to open a new pull request. For example, on the `guessing-game` branch, `git reset --hard 422f001ff84537ca09e357f57f773cdf328b125c`, because https://github.com/exercism/haskell/pull/1109/commits/422f001ff84537ca09e357f57f773cdf328b125c is the head of this pull request's branch.

Finally, I will note that I need to push some commits to this `main` branch, which is the branch being used in this pull request. Please be aware of that if you are going to use this `main` branch in the future.

**Review by petertseng — APPROVED** [review]
Okay, I think we're good to go. Thanks for working on it and enduring my numerous requests to change things in the code and in git.

Others have about 24 hour to object, and if not, this is getting merged.

**Comment by MatthijsBlom** [comment]
The exercise is now visible to students, as is the accompanying concept. However, the syllabus is still hidden. Is this the preferred state?

**Comment by ErikSchierboom** [comment]
> The exercise is now visible to students, as is the accompanying concept. However, the syllabus is still hidden. Is this the preferred state?

@MatthijsBlom I think this is actually a bug. Could you perhaps create an issue at https://github.com/exercism/exercism?

**Comment by ErikSchierboom** [comment]
Great work all!

**Pull request merged**
