### PR TITLE
stack.yaml: lts-12.4 -> lts-14.7

### PR DESCRIPTION
**Pull request by petertseng**
https://www.stackage.org/diff/lts-12.4/lts-14.7

Last update 14 months ago
https://github.com/exercism/haskell/pull/697

I think it would be interesting to get on GHC 8.6.x.

### CODE REVIEW

**Comment by petertseng** [comment]
I see that this subjects every exercise to the README check, and I'm not interested in fixing resistor-colour-duo's README since a change to the tests will be needed. I will take an appropriate action at some point, maybe after work.

**Comment by petertseng** [comment]
Huh, this one went a lot smoother than 12.4 did.

**Comment by sshine** [comment]
I've taken the liberty to assume so.

**Comment by petertseng** [comment]
I do think the merge commit was the better of the choices.

As you can see, the stack version is updated very irregularly, "whenever someone feels like it". It was discussed briefly in https://github.com/exercism/haskell/issues/470 but the conclusion there reached was simply "left to the choice of whoever wants to open the PR", which happened to be me this time.

**Pull request merged**
