### PR TITLE
Reformat config files for reordering

### PR DESCRIPTION
**Pull request by laurafeier**
Result of configlet fmt.
 See exercism/meta#95 

 Created at ROSSConf. /cc @kytrinyx

### CODE REVIEW

**Comment by petertseng** [comment]
Evidence of correctness:

https://travis-ci.org/exercism/haskell/builds/378150526 runs against https://github.com/exercism/haskell/commit/8d296702e970d539b59dec31745b9ef8cb8b1633 and rejects it:

```
$ sh ./bin/check-configlet-fmt.sh
configlet fmt:
-> changes made to: config.json
Please update the PR to incorporate those changes.
The command "sh ./bin/check-configlet-fmt.sh" exited with 1.
```

**Comment by petertseng** [comment]
ok, thanks

**Comment by kytrinyx** [comment]
FYI a couple of tweaks have been requested to the configlet fmt command:

exercism/configlet#129
exercism/configlet#128

This means that there will be (yet) another fmt PR forthcoming in the future.

**Comment by petertseng** [comment]
Understood.

**Pull request merged**
