### PR TITLE
Update stack.yml to lts-18.14

### LINKED ISSUE #948: Migrate all exercises to lts-17 (GHC 8.10)
On 2021-01-24 [lts-17.0](https://www.stackage.org/lts-17.0) (supporting GHC 8.10.3) was released.

We would like to eventually bump the resolver in each exercise's stack.yaml.

If there are any dependencies that still have not been ported, then that could justify waiting a bit.

Unless something has changed since [#877](https://github.com/exercism/haskell/pull/877#issuecomment-727140640) (bug described in #847, solution discussed in #864), making random changes to each exercise's test file is still necessary for the updated stack.yaml to get distributed.

A quick LTS migration history:
 - #926 (lts-15.8 -> lts-16.21)
 - #905 (lts-14.7 -> lts-15.8)
 - #846 (lts-12.4 -> lts-14.7)
 - #697 (lts-11.19 -> lts-12.4)
 - ...
 - #668 (lts-10.2 -> lts-11.1)
 - #635 (lts-9.11 -> lts-10.2)
 - #619 (lts-8.21 -> lts-9.11)
 - #571 (lts-8.2 -> lts-8.21)
 - ...

### PR DESCRIPTION
**Pull request by tejasbubane**
Last updated almost a year ago: https://github.com/exercism/haskell/pull/926

Closes #948

### CODE REVIEW

**Review by petertseng — APPROVED** [review]
accept, with thanks. to be merged forthwith.

18.14 is the latest LTS resolver, and it was published 2021-10-24. It uses GHC 8.10.7. There is not yet an LTS resolver that uses GHC 9.0.1, so that will have to wait.

TBD: Will students get new version of stack.yaml automatically, or must we still make an inconsequential change to each test file

**Comment by petertseng** [comment]
Tested with an exercise that I had already started before merging this PR: stack.yaml still contains 16.21. I suppose it will be necessary to update the tests then.

**Comment by tejasbubane** [comment]
@petertseng AFAIK old exercises are freezed at the point when you first started/downloaded them - so these changes won't reflect there. I just download a new exercise and can see the new lts version (18.14) in the `stack.yml`. I don't think any further updates are required.

**Comment by petertseng** [comment]
Well, is it possible you don't see that button because we haven't changed the test files, so the website doesn't know that it needs to show you the button?

However, since for this change the button would just be allowing them to update stack.yml, I suppose if they really want to do it they can just change the file themselves. So I suppose it's not a priority.

**Pull request merged**
