### PR TITLE
Rename deprecated hints files

### PR DESCRIPTION
**Pull request by kytrinyx**
The ./exercises/:slug/HINTS.md file has been deprecated in favor of the
./exercises/:slug/.meta/hints.md file.

See https://github.com/exercism/meta/issues/94

### CODE REVIEW

**Comment by petertseng** [comment]
Welcome to squash that commit or not, the commit message was designed to allow either.

**Comment by kytrinyx** [comment]
Thanks, @petertseng

**Comment by petertseng** [comment]
My mistake in not actually adding the commit to this PR. I'll get it sorted.

**Comment by kytrinyx** [comment]
I think this was my mistake. I'm guessing I rebased onto master without pulling down your changes first.

**Pull request merged**
