### PR TITLE
Fix indentation for fenced block in bulleted list

### PR DESCRIPTION
**Pull request by jrib**
Fence marks were visible at exercism.io.

### CODE REVIEW

**Comment by jrib** [comment]
Thanks for explaining how that works.  I think I made the changes match in `README.md` and `hints.md` but the build is still failing.  I'll clone it locally later today and figure out what's going on

**Comment by jrib** [comment]
@sshine  I went ahead and updated the `README.md` from problem-specification, but I see now you just opened #830 open for that...  Well, tests are passing here now.  Let me know if you want me to delete the commit here that updates from problem-description

**Comment by sshine** [comment]
@jrib: Yes, I'm sorry, I'd set up that PR and just as I was about to recommend that you either rebase on top of it or wait until it's merged and rebase on top of master, my screen froze.

I've rebased your feature branch on top of #830, so that when it's ready to be rebased into master, this one is ready as well.

**Comment by jrib** [comment]
No worries.  Thanks for the help!

**Pull request merged**
