### PR TITLE
Various bug fixes and clarifications in Approaches

### PR DESCRIPTION
**Pull request by MatthijsBlom**

### CODE REVIEW

**Review by NgWenYang — APPROVED** [review]
As a student studying alternative approaches to the solution, the added clarification has certainly eliminated some confusion.

**Comment by MatthijsBlom** [comment]
@NgWenYang are you still confused about anything?

If not then I'll ask for merging.

**Comment by NgWenYang** [comment]
@MatthijsBlom No, I am good with the Collatz Conjecture exercise.

**Comment by MatthijsBlom** [comment]
@ErikSchierboom This is ready to be merged.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
