### PR TITLE
Update config.json for files.solution to include package.yaml. Resolves #1003, resolves #1076

### LINKED ISSUE #1003: Data.Set failing to import in solution
When trying to use `Data.Set` in my solution to Pangram, using the online editor, I get the following compilation error
```
[1 of 2] Compiling Pangram

/mnt/exercism-iteration/src/Pangram.hs:9:1: error:
    Could not load module ‘Data.Set’
    It is a member of the hidden package ‘containers-0.6.2.1’.
    Perhaps you need to add ‘containers’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
9 | import qualified Data.Set as S
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

--  While building package pangram-2.0.0.12 (scroll up to its section to see the error) using:
      /opt/test-runner/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build lib:pangram test:test --ghc-options &quot;&quot;
    Process exited with code: ExitFailure 1
```

In the mentor notes for Pangram, it suggests a solution using `Data.Set` so I tried implementing it myself. It seems like it used to work but no longer does.

### LINKED ISSUE #1076: Allow editing of package.yaml in web editor by adding it to files.solution
To allow students to edit the package.yaml, for **each exercise**'s `.meta/config.json`, add `package.yaml` `files.solution`, such as:

```json
  "files": {
    "solution": [
      "src/Accumulate.hs",
      "package.yaml"
    ],    
    "test": [
      "test/Tests.hs"
    ],    
    "example": [
      ".meta/examples/success-standard/src/Accumulate.hs"
    ]     
  }, 
```

This applies to all exercises under `exercises/concept` and `exercises/practice`.

You should also add `package.yaml` to `files.solution` in https://github.com/exercism/haskell/blob/main/config.json, which can be of use when creating new exercises.

In your commit message please use a word from https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue to say that the commit closes these two issues

* https://github.com/exercism/haskell/issues/1003
* https://github.com/exercism/haskell/issues/1076 (this issue)

### PR DESCRIPTION
**Pull request by isaacvando**
Update config.json for files.solution to include package.yaml. Resolves #1003, resolves #1076.

This change will allow users to edit the package.yaml file for each exercise in the online editor. This will allow importing libraries such as Data.Set in the online editor. 

Please let me know if there is anything I can improve in future PRs.

Thanks!

### CODE REVIEW

**Comment by isaacvando** [comment]
Is there any way to test changes like this locally? I looked but was not able to figure anything out.

**Review by petertseng — COMMENTED** [review]
I wish I had a good answer for you about testing this locally, but I do not currently know of a good way to do that.

So far so good on this PR. Please be sure to also do the same to https://github.com/exercism/haskell/blob/main/exercises/concept/temperature/.meta/config.json, which as of this moment isn't being changed in this PR but should be.

**Comment by isaacvando** [comment]
Good catch, I've now updated the config file for temperature also.

**Comment by ErikSchierboom** [comment]
> Is there any way to test changes like this locally? I looked but was not able to figure anything out.

There isn't really. The changes look good to me though.

**Review by petertseng — APPROVED** [review]
this PR changes 104 files, all config.json. There are 107 config.json in this repo, and the ones that are rightfully excluded from this PR are:

./docs/config.json
./concepts/basics/.meta/config.json
./concepts/numbers/.meta/config.json

Therefore, this PR makes all the expected changes

**Comment by petertseng** [comment]
The Haskell track is very grateful that you were willing to take the time and effort to contribute this change to improve the track for all. Thank you!

**Comment by isaacvando** [comment]
I'm very glad I could help!

**Pull request merged**
