### PR TITLE
Sync exercise docs for most exercises

### PR DESCRIPTION
**Pull request by IsaacG**
Sync exercise docs for most exercises where the sync does not change content meaning significantly.

Some exercises have content which would change meaning a bit with a sync and were excluded from this PR.

### CODE REVIEW

**Comment by IsaacG** [comment]
Forum topic: https://forum.exercism.org/t/instructions-in-erlang-saddle-points-are-unclear-or-corrupted/6419/5

**Review by MatthijsBlom — APPROVED** [review]
Looks entirely good to me 👍

**Review by ErikSchierboom — APPROVED** [review]

**Comment by iHiD** [comment]
FYI, this shouldn't have been merged until we add the support for skip test runs, as it's caused every haskell solution to rerun.

**Comment by MatthijsBlom** [comment]
Is there a way I could have known?

**Pull request merged**
