### PR TITLE
Number Theory topic

### PR DESCRIPTION
**Pull request by Average-user**
These are the exercise that I think that should have "Number Theory" as a topic.

### CODE REVIEW

**Comment by petertseng** [comment]
Too hard to read the diff and determine which exercises got the topic. Easier to `ruby -rjson -e 'puts JSON.parse(File.read("config.json"))["exercises"].select { |e| e["topics"]&.include?("Number Theory") }.map { |e| e["slug"] }' | sort`
collatz-conjecture
difference-of-squares
largest-series-product
nth-prime
pascals-triangle
prime-factors
pythagorean-triplet
sieve
sum-of-multiples
triangle

**Comment by petertseng** [comment]
I think I agree with all of these. I'm unsure about largest-series-product since it's just multiplying numbers and comparing them, but whatever.

I think complex-numbers should have.

Maybe grains should have, but I'm not sure.

**Comment by Average-user** [comment]
@petertseng Should I do a squash?

**Comment by petertseng** [comment]
> Should I do a squash?

Optional, because if you don't, I will. But that also means you are welcome to do it.

**Comment by Average-user** [comment]
@petertseng How do you squash? ``` reset --soft```?

**Comment by petertseng** [comment]
> How do you squash?

I interpreted this question as asking, how do **I** do it? I use `git rebase -i master`.

You can use whatever you want that achieves the same effect. I haven't used `reset --soft` before but if it works, it works.

**Comment by Average-user** [comment]
@petertseng  Ok thanks.

>but if it works, it works.

Looks to be your style jeje.

**Comment by petertseng** [comment]
collatz-conjecture
complex-numbers
difference-of-squares
grains
nth-prime
pascals-triangle
prime-factors
pythagorean-triplet
sieve
sum-of-multiples
triangle

**Comment by petertseng** [comment]
I would think either both grains and largest-series-product have the topic, or neither do. I don't know which is right since I don't know what number theory is. My guess is no.

Weren't you going to squash??

**Comment by Average-user** [comment]
@petertseng I think you were right about taking off largest-series-product, and adding grains. I know that to solve grains you don't really do much, but it still a classic problem, I just didn't realize that grains is the name for it.

**Comment by petertseng** [comment]
Oh, so you think this list is good as-is. OK then.

**Pull request merged**
