### PR TITLE
adding Isogram

### PR DESCRIPTION
**Pull request by Average-user**
Another Unimplemented exercise

### CODE REVIEW

**Comment by petertseng** [comment]
Please only include changes about isogram and not collatz conjecture. Please ask if you need help on how to achieve this (interactive rebase on Exercism's master branch, leave only "adding isogram")

**Comment by petertseng** [comment]
In case we lose it, the adding isogram commit was originally bde336fc68f66c6362c2959b2b8aac8ce61f9621

**Comment by Average-user** [comment]
ok i'll close this and start a new one

**Comment by petertseng** [comment]
I don't understand why you have to close this one and start a new one. You can just reuse this one. But you can do as you like.

**Pull request closed without merging**
