### PR TITLE
nucleotide-count: Use data type to represent nucleotides

### PR DESCRIPTION
**Pull request by sshine**
Preserve the Data.Map.

References #964

### CODE REVIEW

**Comment by petertseng** [comment]
(so please fix to use correct issue number)

**Comment by sshine** [comment]
@petertseng With a few tries, I've addressed both issues.

And yes, I figured accepting broken strings was in the spirit of the assignment, like broken DNA. :-)

**Comment by petertseng** [comment]
Very good, thank you!

**Comment by sshine** [comment]
Three months later, giving my first review to this exercise and realizing my own version doesn't have the `data Nucleotide` definition, I ask myself: "Who the hell added this in the meantime?"

**Pull request merged**
