### PR TITLE
roman-numerals: test for Nothing

### PR DESCRIPTION
**Pull request by kephas**

### CODE REVIEW

**Comment by MatthijsBlom** [comment]
@ErikSchierboom no objections from me.

**Comment by ErikSchierboom** [comment]
@kephas You'll also need to update the example implementation: https://github.com/exercism/haskell/blob/main/exercises/practice/roman-numerals/.meta/examples/success-standard/src/Roman.hs

**Comment by kephas** [comment]
Now the example passes the new tests.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks

**Pull request merged**
